name: Linux

on:
  push:

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        architecture: [x64]
        qt-version: [5.15.0, 6.3.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt-version }}
          archives: 'qtbase icu'
          cache: 'true'

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-12 g++-12

      - name: Configure
        run: |
          export CC=gcc-12 && export CXX=g++-12
          cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build
        working-directory: build
        run: |
          make -j$(nproc)

      - name: Test
        working-directory: build
        run: |
          ./examples/qntp_example
